name: harucourt
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  get: ^4.7.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-Bold.otf
    - family: Ownglyph
      fonts:
        - asset: assets/fonts/Ownglyph.ttf
